### ISSUE TITLE
Connect to console need to check for existence of designated IP address

### ISSUE THREAD

**Issue by hliu9** [jrsaunde/PathDrop#19]
Find Neighbors, should constantly update an global array list of discovered IP address.

**Comment by hliu9** [comment]
There is an global static ArrayList variable "discoveredIPs" created in GuiFx.java
The reference is passed into the NetworkDiscovery's global variable also named "discoveredIPs". 

Before proceeding with connecting to a device, we will need to add IPs (strings) into the ArrayList in the getNeighbors() method.

**Comment by jrsaunde** [comment]
This is done, tested and works with VTY
