### ISSUE TITLE
Resizing VTY window

### ISSUE THREAD

**Issue by jrsaunde** [jrsaunde/PathDrop#21]
We can resize when dragging the window to the right, the grey box follows and the output rearrages.

But when we resize downwards, the grey box does not resize with it

**Comment by hliu9** [comment]
yea, noticed that, will fix that after beta

**Comment by hliu9** [comment]
there are other minor re-sizing issues as well

**Comment by jrsaunde** [comment]
Yup, the resizing of the Topology area needs to be fixed, right now the Legend overlaps the topology, and we can drag to resize it

**Comment by hliu9** [comment]
Fixed
